/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package locatemecheck;

import java.awt.event.KeyEvent;


/**
 *
 * @author Teckos
 */
public class Liste_Imei extends javax.swing.JFrame {
 
    /**
     * Creates new form NewJFrame
     */
    public Liste_Imei() {
        
        initComponents();
      
        IMEI.requestFocus();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LISTE = new javax.swing.JTextArea();
        IMEI = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.white);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N
        jLabel2.setText("Powered by Teckos / 3R   -   v2.0");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        LISTE.setColumns(20);
        LISTE.setRows(5);
        LISTE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LISTEKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(LISTE);

        IMEI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IMEIActionPerformed(evt);
            }
        });
        IMEI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                IMEIKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(12, 12, 12))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(IMEI))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(IMEI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
        
    
    
    
   
    
    private void LISTEKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LISTEKeyPressed
        
        
       
             
             
             
         
    }//GEN-LAST:event_LISTEKeyPressed

    private void IMEIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IMEIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IMEIActionPerformed

    private void IMEIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IMEIKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            String TXT=IMEI.getText();
            //System.out.println(LISTE.getLineCount());
            if (LISTE.getText().isEmpty()==false) {LISTE.append("\n");
                              LISTE.paintImmediately(LISTE.getBounds ());
                                LISTE.update(LISTE.getGraphics());}
             if ((TXT.length() == 17)&(TXT.startsWith("A"))&(TXT.endsWith("B")))
                          {
                              TXT=TXT.substring(1, 16);
                              LISTE.append(TXT);
                              LISTE.paintImmediately(LISTE.getBounds ());
                                LISTE.update(LISTE.getGraphics());
                                IMEI.setText("");
                                IMEI.requestFocus();
                          }
             else if ((TXT.length() == 15))
             {
                 LISTE.append(TXT);
                              LISTE.paintImmediately(LISTE.getBounds ());
                                LISTE.update(LISTE.getGraphics());
                                IMEI.setText("");
                                IMEI.requestFocus();
             }
             
        }
    }//GEN-LAST:event_IMEIKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Liste_Imei.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Liste_Imei.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Liste_Imei.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Liste_Imei.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Liste_Imei().setVisible(true);
                
            }
            
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IMEI;
    private javax.swing.JTextArea LISTE;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
